config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  resources :items do
    resources :bookings, only: [:create]
  end
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  resources :bookings, only: [:index, :destroy] do
    resources :item_reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :item_review, dependent: :destroy

  validates :price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :item_reviews, through: :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :price, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :photo, presence: true
  validates :address, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/item_review.rb
class ItemReview < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true
  validates :content, presence: true
end

app/models/renter_review.rb
class RenterReview < ApplicationRecord
  belongs_to :booking
  belongs_to :user

  validates :rating, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :items

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/ || users_controller?
  end

  def users_controller?
    controller_name == "users" || controller_name == "item_reviews" || controller_name == "bookings"
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_item, only: [:new, :create]
  before_action :set_booking, only: [:destroy]

  def index
    @bookings = Booking.all
  end

  def create
    prevent_owner
    @booking = Booking.new(booking_params)
    @booking.price = @item.price
    @booking.item = @item
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      redirect_to @item
    end
  end

  def destroy
    @booking.destroy
    @item = @booking.item
    redirect_to @item
  end

  private

  def prevent_owner
    redirect_to @item if current_user == @item.user
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/item_reviews_controller.rb
class ItemReviewsController < ApplicationController

  def create
    @booking = Booking.find(params[:booking_id])
    redirect_to dashboard_path if @booking.item_review #hacker defense
    @user = current_user
    @item_review = ItemReview.new(item_review_params)
    @item_review.booking = @booking
    if @item_review.save
      redirect_to @item_review.booking.item
    else
      flash[:alert] = "Review invalid"
      render 'users/dashboard'
    end
  end

  private

  def item_review_params
    params.require(:item_review).permit(:rating, :content)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = policy_scope(Item).where.not(latitude: nil, longitude: nil)

    if params[:category].present?
      @items = @items.where(category: params[:category])
    end

    if params[:itemname].present?
      @items = @items.where("name ILIKE ?", "%#{params[:itemname]}%")
    end

    if params[:location].present?
      @items = @items.where("address ILIKE ?", "%#{params[:location]}%")
    end

    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        infoWindow: { content: render_to_string(partial: "/items/map_box", locals: { item: item }) }
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @item = current_user.items.new
    authorize @item
  end

  def create
    @item = current_user.items.new(item_params)
    authorize @item
    if @item.valid?
      @item.save
      redirect_to @item
    else
    render 'new'
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
    if @item.valid?
      @item.save
      redirect_to @item
    else
    render 'edit'
    end
  end

  def destroy
    @item.destroy
  end

  private
  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end

  def item_params
    params.require(:item).permit(:price, :name, :description, :category, :photo, :address, :published)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @items = Item.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    @user = current_user
    @item_review = ItemReview.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/items/_map_box.html.erb
<div>
  <p>
    <%= item.name %> - <%= item.address %>
  </p>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="form-header">
    <h2 class="text-center">Tell us about your Item</h2>
  </div>
  <div class="newitemform-container">
    <%= render 'shared/item_form' %>
  </div>
</div>

app/views/items/index.html.erb
<div class="searchbar-box">
  <%= form_tag("/items", class: "form", method: "get") do %>
    <div class="col-xs-10 col-xs-offset-1 col-md-2 col-md-offset-0 colpadd">
      <%= select_tag "category", options_for_select(Item.all.pluck(:category).uniq), include_blank: "All", class: "form-control" %>
    </div>
    <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-0 colpadd">
       <%= text_field_tag :itemname, nil, placeholder: "What would you like to rent?", class: "form-control keyword" %>
     </div>
     <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-0 colpadd">
      <%= text_field_tag :location, nil, placeholder: "Where would you like to rent?", class: "form-control input" %>
    </div>
    <div class="col-xs-10 col-xs-offset-1 col-md-2 col-md-offset-0 colpadd">
      <%= submit_tag("Search Now", id: "searchbtn", class: "button")  %>
    </div>
  <% end %>
</div>
<div class="container-fluid marged">
  <div class="row">
    <div class="col-md-7">
      <div class="row">
        <% @items.each do |item| %>
          <% if item.published %>
          <%= link_to item_path(item) do %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="row-margin">
                <%= render 'shared/card', item: item %>
            </div>
          </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-5 map-container">
      <div id="map" data-markers="<%= @markers.to_json %>"></div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="form-header">
    <h2 class="text-center">Tell us about your Item</h2>
  </div>
  <div class="newitemform-container">
    <%= render 'shared/item_form' %>
  </div>
</div>

app/views/items/show.html.erb
<div class="product-banner bg-<%=@item.category.downcase%>"></div>
<div class="container-fluid padded">
  <div class="row">
    <div class="col-md-8 product-detail">
      <div class="product-name">
        <h1><%= @item.name %></h1>
        <p><%= @item.address %></p>
        <p><strong>Daily Rate: <%= @item.price %> €</strong></p>
      </div>
      <div class="product-photo">
        <%= cl_image_tag @item.photo %>
      </div>
      <div class="container product-description">
        <div class="row">
          <div class="col-md-8">
            <h3>Description</h3>
            <p><%= @item.description %></p>
          </div>
          <div class="col-md-4">
            <%= image_tag 'tent.png' %>
          </div>
        </div>
      </div>
      <div class="reviews-container">
        <%= render 'shared/reviews-container' %>
      </div>
      <div class="linkto-search">
        <%= link_to "Back to Search", items_path %>
      </div>
    </div>
    <div class="col-md-4 booking-form">
    <% if @item.user != current_user %>
      <div class="booking-card">
        <h2>Your booking</h2>
        <div class="bookingform">
          <%= render "shared/booking-form", item:@item, booking:@booking %>
        </div>
        <hr>
        <ul class="guarantees">
          <li><i class="far fa-check-square"></i></i> Inmediate response</li>
          <li><i class="far fa-check-square"></i></i> Close to you</li>
          <li><i class="far fa-check-square"></i></i> Guaranteed assistance</li>
        </ul>
        <hr>
        <div class="secure-payment">
          <p>Secure Payment</p>
          <div class="payments">
            <i class="fab fa-cc-amex"></i>
            <i class="fab fa-cc-stripe"></i>
            <i class="fab fa-cc-apple-pay"></i>
          </div>
        </div>
      </div>
    <% else %>
      <h3>This is your Listing!</h3>
      <% if policy(@item).edit? %>
        <%= link_to "Edit", edit_item_path(@item) %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>eQuip</title>
    <meta name="description" content="Make money off your adventure gear. Reasonable prices from owners around the world."/>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body class="<%= yield (:body_class) %>">
    <% if controller_name == 'pages' && action_name == "home" %>
      <%= render "shared/transparent-navbar" %>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

<div class="container-fluid">
  <h2 class="home-title">Recent Items</h2>
  <div class="row padded row-margin">
    <% @items.first(4).each do |item| %>
      <%= link_to item_path(item) do %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <%= render 'shared/card', item: item %>
      </div>
      <% end %>
    <% end %>
</div>
</div>

<div class="container-fluid bck-white">
  <h2 class="home-title">Snow</h2>
  <div class="row padded row-margin">
    <% @items.where(category: "Snow").first(4).each do |item| %>
      <%= link_to item_path(item) do %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <%= render 'shared/card', item: item %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <h2 class="home-title">Wind</h2>
  <div class="row padded row-margin">
    <% @items.where(category: "Wind").first(4).each do |item| %>
      <%= link_to item_path(item) do %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <%= render 'shared/card', item: item %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container-fluid bck-white">
  <h2 class="home-title">Water</h2>
  <div class="row padded row-margin">
    <% @items.where(category: "Water").first(4).each do |item| %>
      <%= link_to item_path(item) do %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <%= render 'shared/card', item: item %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <h2 class="home-title">Outdoors</h2>
  <div class="row padded row-margin">
    <% @items.where(category: "Outdoor").first(4).each do |item| %>
      <%= link_to item_path(item) do %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <%= render 'shared/card', item: item %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner-wrapper">
  <div class="banner-home">
    <div class="banner-content">
      <div class="banner-c2a">
        <h1 class="heading"><b>Rent</b> tested sports eQuipment</h1>
        <p class="paragraph">Find the items you need, where you need them</p>
      </div>
      <div class="searchbar-container">
        <div class="row">
          <%= form_tag("/items", class: "form", method: "get") do %>
            <div class="col-xs-10 col-xs-offset-1 col-md-2 col-md-offset-0 colpadd">
              <%= select_tag "category", options_for_select(Item.all.pluck(:category).uniq), include_blank: "All", class: "form-control" %>
            </div>
            <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-0 colpadd">
               <%= text_field_tag :itemname, nil, placeholder: "What would you like to rent?", class: "form-control keyword" %>
             </div>
             <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-0 colpadd">
              <%= text_field_tag :location, nil, placeholder: "Where would you like to rent?", class: "form-control input" %>
            </div>
            <div class="col-xs-10 col-xs-offset-1 col-md-2 col-md-offset-0 colpadd">
              <%= submit_tag("Search Now", id: "searchbtn", class: "button")  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="advantages">
      <div><%= image_tag("feather.svg", class: "advantages-img") %>Travel Light</div>
      <div><%= image_tag("piggy.svg", class: "advantages-img") %>Save Time & Money</div>
      <div><%= image_tag("balance.svg", class: "advantages-img") %>Compare Offers</div>
      <div><%= image_tag("help.svg", class: "advantages-img") %>Help 24/7</div>
    </div>
  </div>
</div>
<div id="homecarousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3500">
  <div class="carousel-inner">
    <div class="active item">
      <div class="carousel-gradient"></div>
      <%= image_tag "snowboard.jpg" %>
    </div>
    <div class="item">
      <div class="carousel-gradient"></div>
      <%= image_tag "tenis.jpg" %>
    </div>
    <div class="item">
      <div class="carousel-gradient"></div>
      <%= image_tag "bike.jpg" %>
    </div>
    <div class="item">
      <div class="carousel-gradient"></div>
      <%= image_tag "skate.jpg" %>
    </div>
  </div>
</div>

app/views/shared/_booking-form.html.erb
<%= simple_form_for [item, booking] do |f| %>
  <%= f.input :start_date, as: :string %>
  <%= f.input :end_date, as: :string %>
  <%= f.submit :submit, class:"btn btn-success booking-btn", value:"Book your item" %>
<% end %>

app/views/shared/_card.html.erb
<div class="card">
  <div class="card-content" style="background-image: url(<%= cl_image_path item.photo %>);">
  </div>
  <div class="card-footer">
    <div class="category">- <%= item.category %> -</div>
    <div class="card-name"><h4><%= item.name %></h4></div>
    <div class="card-price"><strong><%= item.price %>€</strong>/day</div>
    <div class="card-rating">
      <% rating = item.item_reviews.last.rating if item.item_reviews.last %>
      <% if rating %>
        <% rating.times do %>
        <i class="fas fa-star"></i>
        <% end %>
        <% (5 -(rating)).times do %>
        <i class="far fa-star"></i>
        <% end %>
      <% end %>
      <span> · <%= item.user.first_name %></span>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible <%= "alert-fixed" if action_name == "home" %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible <%= "alert-fixed" if action_name == "home" %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_item_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :name %>
  <%= f.input :description, hint: "What does your renter need to know? (size, quantity, quality, etc.)" %>
  <%= f.input :price, label: "Price per day"%>
  <%= f.input :category, collection: ["Snow", "Water", "Wind", "Outdoor"] %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :address %>
  <%= f.input :published %>
  <%= f.submit :submit, class:"button", value:"Post your item" %>
<% end %>
<div id="cancel-button">
  <%= link_to "Cancel", :back, class: "button button-red"%>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-white">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag("logo.png") %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Add eQuipment", new_item_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log In", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
           <%= image_tag "http://kitt.lewagon.com/placeholder/users/vananreed", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", dashboard_path %></li>
            <li><%= link_to "eQuip Up!", items_path %></li>
            <li><%= link_to "Add eQuipment", new_item_path %></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <%= image_tag "http://kitt.lewagon.com/placeholder/users/vananreed", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", dashboard_path %></li>
          <li><%= link_to "eQuip Up!", items_path %></li>
          <li><%= link_to "Add eQuipment", new_item_path %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Add eQuipment", new_item_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_reviews-container.html.erb
<h3>Reviews</h3>
<div class="reviews">
  <% if @item.item_reviews.presence %>
  <%= image_tag "http://kitt.lewagon.com/placeholder/users/zentuco", class: "avatar" %>
  <% @item.item_reviews.each do |review| %>
  <div class="review-name">
    <%= review.booking.user.first_name %>
  </div>
  <div class="review-body">
    <%= review.content %>
  </div>
  <div class="review-rating">
    <% review.rating.times do %>
    <i class="fas fa-star"></i>
    <% end %>
    <% (5 -(review.rating)).times do %>
    <i class="far fa-star"></i>
    <% end %>
  </div>
  <% end %>
  <% else %>
  No Reviews yet!
  <% end %>
</div>

app/views/shared/_transparent-navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag("logo.png") %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Add eQuipment", new_item_path, class:"navbar-wagon-item navbar-wagon-link-white" %>
    <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-link-white" %>
      <%= link_to "Log In", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link-white" %>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
           <%= image_tag "http://kitt.lewagon.com/placeholder/users/vananreed", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", dashboard_path %></li>
            <li><%= link_to "eQuip Up!", items_path %></li>
            <li><%= link_to "Add eQuipment", new_item_path %></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <%= image_tag "http://kitt.lewagon.com/placeholder/users/vananreed", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", dashboard_path %></li>
          <li><%= link_to "eQuip Up!", items_path %></li>
          <li><%= link_to "Add eQuipment", new_item_path %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Add eQuipment", new_item_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<div class="container">
  <div class="dashboard">
    <div class="your-info">
      <div>
        <div class="name">Hi, <%= @user.first_name %> <%= @user.last_name %>! </div>
        <div><%= @user.email %></div>
      </div>
    </div>
    <div class="bookings">
      <h2 class="margin-left">Your Bookings</h2>
      <% if @user.bookings.presence %>
      <div class="row">
        <% @user.bookings.each do |booking| %>
        <div class="booking">
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= link_to item_path(booking.item) do %>
            <%= render 'shared/card', item: booking.item %>
            <% end %>
            <div class="booking-details text-center">
              <div>Booking ID: <%= booking.id %></div>
              <div>Start date: <%= booking.start_date.strftime("%m/%d/%Y") %></div>
              <div class="end-date">End date: <%= booking.end_date.strftime("%m/%d/%Y") %></div>
              <%= link_to "Cancel this Booking", booking_path(booking), class: "button button-red", :method => :delete, data: {:confirm => "You sure?" } %>
            </div>
            <div class="add-review">
              <% if !booking.item_review %>
              <%= simple_form_for [booking, @item_review] do |f|%>
              <%= f.input :rating, collection: [1,2,3,4,5] %>
              <%= f.input :content %>
              <%= f.submit "Add Review", class: "button" %>
              <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% else %>
      <div class="booking">
        You don't have any bookings yet!
      </div>
      <%= link_to "Browse Items", items_path, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="user-items">
      <div class="row">
        <h2 class="margin-left">Your Listed Items</h2>
        <% if @user.items.presence %>
        <% @user.items.each do |item|%>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
          <%= link_to item_path(item) do %>
          <%= render 'shared/card', item: item %>
          <% end %>
          <div>
            <% if item.published? %>
            <p class="published">This item is published</p>
            <% else %>
            <p class="published">This item is not published</p>
            <% end %>
            <%= link_to "Edit", edit_item_path(item), class: "button button-red" %>
          </div>
        </div>
        <% end %>
        <% else %>
        <div class="no-items">
          You haven't listed any items yet!
        </div>
        <%= link_to "List an Item now", new_item_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>